### PR TITLE
fix: add new example to use existing kms

### PR DESCRIPTION
**Pull request by maheshwarishikha**
### Description

Adds new example to create keyring within existing KMS.

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [x] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
A few points:
1. It would be better to keep any one of the examples, not both. As they both are very similar.
2. But if you decide to keep both of them, then I'd recommend you make a change in the "default" example, to consume [https://github.com/terraform-ibm-modules/terraform-ibm-key-protect](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect) module to create the Key protect instance. Right now, it creates on its own using Terraform.
3. Also, please add a new test for the example as well. Maybe in the `other_test.go`. To make that test work you need to spin up a permanent Key Protect instance. You can do that here https://github.ibm.com/GoldenEye/ge-dev-account-management/blob/master/main.tf

**Comment by maheshwarishikha** [comment]
> A few points:
> 
>     1. It would be better to keep any one of the examples, not both. As they both are very similar.
> 
>     2. But if you decide to keep both of them, then I'd recommend you make a change in the "default" example, to consume https://github.com/terraform-ibm-modules/terraform-ibm-key-protect module to create the Key protect instance. Right now, it creates on its own using Terraform.
> 
>     3. Also, please add a new test for the example as well. Maybe in the `other_test.go`. To make that test work you need to spin up a permanent Key Protect instance. You can do that here https://github.ibm.com/GoldenEye/ge-dev-account-management/blob/master/main.tf

@rajatagarwal-ibm 
1. Going forward, this repo will be used as KMS i.e. for KP and HPCS. So in one of the discussion...the idea of adding a new example came out hence the example was added. So we'll keep both the examples.
2. As this example was added to make this repo ready for HPCS, so lets merge this PR. Request to change example 1 - will address as a separate issue - #5153 . I can pick this up after HPCS activities.
3. I do not think if we really need a test for this...as it is just creating keyring which anyways is getting tested in default example.

Let me know your thoughts. Thanks

**Comment by rajatagarwal-ibm** [comment]
Alright if you want to address some of the points in the separate PR. I will approve this one.

Also, in case this module supports HPCS then perhaps we need to rename this module from Key Protect to Key Management. 

I think in that case we can add a test pointing to the existing HPCS instance. That will give coverage to both KP and HPCS KMS services.

**Review by rajatagarwal-ibm — APPROVED** [review]

**Comment by maheshwarishikha** [comment]
yes, KP -> KMS change is the next that is coming for this module. Addressing that via #5141.

**Pull request merged**
